folio-org/mod-dcb

pom.xml, src/main/java/org/folio/dcb/controller/TransactionApiController.java, src/main/java/org/folio/dcb/controller/advice/TransactionsExceptionHandler.java, src/main/java/org/folio/dcb/domain/converter/PostgresUUIDConverter.java, src/main/java/org/folio/dcb/domain/entity/Transactions.java, src/main/java/org/folio/dcb/mapper/TransactionStatusMapper.java, src/main/java/org/folio/dcb/repository/TransactionsRepository.java, src/main/java/org/folio/dcb/service/TransactionService.java, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/sql/2023-08-17-01__create_transaction_table.sql, src/main/resources/db/changelog/changes/sql/2023-09-13_transaction_table_total_rebuild.sql, src/main/resources/db/changelog/changes/transactions_table_changes_schema.xml, src/main/resources/swagger.api/dcb_transaction.yaml, src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java, src/test/java/org/folio/dcb/service/TransactionServiceTest.java
=> MODDCB-1: Implement GET API for DCB Transaction

src/main/java/org/folio/dcb/service/impl/UserServiceImpl.java, src/test/java/org/folio/dcb/utils/EntityUtils.java
The purpose of the Jira is to apply user type as DCB for a user that is created for lending role.
While creating user pass dcb as the value for usertype.
=> MODDCB-30 - Apply User type as DCB for the User that is created.

src/main/java/org/folio/dcb/client/feign/CirculationClient.java, src/main/java/org/folio/dcb/domain/entity/TransactionEntity.java, src/main/java/org/folio/dcb/domain/mapper/TransactionMapper.java, src/main/java/org/folio/dcb/listener/CirculationCheckInEventListener.java, src/main/java/org/folio/dcb/service/CirculationService.java, src/main/java/org/folio/dcb/service/LibraryService.java, src/main/java/org/folio/dcb/service/impl/CirculationServiceImpl.java, src/main/java/org/folio/dcb/service/impl/LendingLibraryServiceImpl.java, src/main/java/org/folio/dcb/service/impl/TransactionsServiceImpl.java, src/main/java/org/folio/dcb/utils/TransactionHelper.java, src/main/resources/application.yml, src/main/resources/swagger.api/dcb_transaction.yaml, src/main/resources/swagger.api/schemas/checkOutRequest.yaml, src/main/resources/swagger.api/schemas/dcbTransaction.yaml, src/main/resources/swagger.api/schemas/transactionStatusResponse.yaml, src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java, src/test/java/org/folio/dcb/listener/CirculationCheckInEventListenerTest.java, src/test/java/org/folio/dcb/service/LendingLibraryServiceTest.java, src/test/java/org/folio/dcb/service/TransactionServiceTest.java, src/test/java/org/folio/dcb/utils/EntityUtils.java, src/test/resources/mappings/circulation.json, src/test/resources/mockdata/kafka/check_in_error.json
[MODDCB-20](https://issues.folio.org/browse/MODDCB-20)
[MODDCB-12](https://issues.folio.org/browse/MODDCB-12)
=> [MODDCB-20]-Added Checkout status process.

src/main/java/org/folio/dcb/service/impl/CirculationItemServiceImpl.java, src/main/resources/swagger.api/schemas/CirculationItemRequest.yaml
https://issues.folio.org/browse/MODDCB-51
for the CirculationItemRequest 
the field name itemBarcode should be changed to barcode
=> MODDCB-51: CirculationItemRequest itemBarcode change to barcode

pom.xml
https://issues.folio.org/browse/MODDCB-65
to fix vulnerability issues
spring-boot-starter-parent --> 3.1.5; 
folio-spring-base --> 7.2.2
=> MODDCB-65: spring-boot-starter-parent --> 3.1.5; folio-spring-base --> 7.2.2

src/main/java/org/folio/dcb/listener/kafka/CirculationEventListener.java, src/main/java/org/folio/dcb/listener/kafka/EventData.java, src/main/java/org/folio/dcb/repository/TransactionRepository.java, src/main/java/org/folio/dcb/utils/TransactionHelper.java, src/test/java/org/folio/dcb/listener/CirculationRequestCancelEventListenerTest.java
Covers: [MODDCB-45](https://issues.folio.org/browse/MODDCB-45)
=> MODDCB-45 Filtering DCB Transaction using request_id

src/main/java/org/folio/dcb/service/impl/TransactionsServiceImpl.java
=> MODDCB-45 Added status check for ITEM_CHECKED_OUT, ITEM_CHECKED_IN

src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java, src/test/java/org/folio/dcb/service/LendingLibraryServiceTest.java
Added CancellationFlow unit tests for Lender Role
=> MODDCB-45 Added unit test for Lender role

README.md, src/main/resources/application.yml
https://issues.folio.org/browse/MODDCB-79
=> MODDCB-79: exposure:include: ${ACTUATOR_EXPOSURE:health,info,loggers}

PERSONAL_DATA_DISCLOSURE.md
The purpose of this Jira is add PERSONAL_DATA_DISCLOSURE.md file for TC evaluation.
The file is added
=> MODDCB-77 - Added PERSONAL_DATA_DISCLOSURE.md file for TC

README.md
=> MODDCB-84 - Updated the README.md file.

src/main/java/org/folio/dcb/client/feign/InventoryItemStorageClient.java, src/main/java/org/folio/dcb/controller/ExceptionHandlingController.java, src/main/java/org/folio/dcb/service/ItemService.java, src/main/java/org/folio/dcb/service/impl/ItemServiceImpl.java, src/main/java/org/folio/dcb/service/impl/RequestServiceImpl.java, src/main/java/org/folio/dcb/service/impl/TransactionsServiceImpl.java, src/main/resources/swagger.api/schemas/InventoryItem.yaml, src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java, src/test/java/org/folio/dcb/service/InventoryItemServiceTest.java, src/test/java/org/folio/dcb/service/RequestServiceTest.java, src/test/java/org/folio/dcb/utils/EntityUtils.java, src/test/resources/mappings/inventory.json
=> MODDCB-86 Handling invalid barcode issue in Lender role

MODULE_SELF_EVALUATION.md
Added MODULE_SELF_EVALUATION.md file for TCR process.
Added the self evaluation file.
=> [TCR-36] - Added MODULE_SELF_EVALUATION.md file.

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> [MODDCB-95]- Q release 1.1.0

src/main/java/org/folio/dcb/listener/kafka/CirculationEventListener.java, src/main/java/org/folio/dcb/listener/kafka/EventData.java, src/main/java/org/folio/dcb/utils/TransactionHelper.java, src/test/java/org/folio/dcb/listener/CirculationLoanEventListenerTest.java, src/test/java/org/folio/dcb/listener/CirculationRequestEventListenerTest.java, src/test/resources/mockdata/kafka/cancel_request_dcb.json, src/test/resources/mockdata/kafka/check_in_dcb.json, src/test/resources/mockdata/kafka/check_in_transit_dcb.json, src/test/resources/mockdata/kafka/check_out_dcb.json, src/test/resources/mockdata/kafka/loan_check_in.json, src/test/resources/mockdata/kafka/loan_sample_without_isdcb.json, src/test/resources/mockdata/kafka/request_sample.json
https://folio-org.atlassian.net/browse/MODDCB-101 
https://folio-org.atlassian.net/browse/MODDCB-102
Request Event:
added a condition in request event listener which checks whether the payload contain instanceTitle as DCB_INSTANCE or requesterLastName as DcbSystem.
Loan Event:
in mod circulation , if the event is related to dcb then a boolean flag isDcb = true is added to the payload , for non dcb events it is false , so in the loan event listener of mod-dcb added a condition which checks whether the event is dcb or non dcb event with the help of isdcb flag
=> Moddcb 102

descriptors/ModuleDescriptor-template.json
To updated the holdings-storage version
=> [MODDCB-106] - API version update

descriptors/ModuleDescriptor-template.json
The purpose of the PR is to implement MODDCB-109
=> MODDCB-109 Added missing permissions for PUT api during cancellation flow

README.md, descriptors/ModuleDescriptor-template.json, src/main/resources/application.yml
Adds a system user description in the module descriptor (see [EUREKA-225](https://folio-org.atlassian.net/browse/EUREKA-225))
- Adds a system user description in the module descriptor to the metadata field
=> EUREKA-225 Add system user to ModuleDescriptor

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> To release 1.1.2

NEWS.md, pom.xml
=> MODDCB-115 - post release 1.1.2

src/main/resources/swagger.api/schemas/CirculationRequest.yaml
Update request schema with position field which is necessary for request reordering in mod-circulation
Resolves: [MODDCB-122](https://folio-org.atlassian.net/browse/MODDCB-122)
=> [MODDCB-122] Add position field to request schema

src/main/java/org/folio/dcb/DcbApplication.java, src/test/java/org/folio/dcb/FolioDcbApplicationTest.java
https://folio-org.atlassian.net/browse/MODDCB-121
removed SYSTEM_USER_PASSWORD check from main method
=> MODDCB-121 SYSTEM_USER env var is not taking affect

NEWS.md, pom.xml
The purpose of the PR is to update News md file and change the snapshot version in master after release of 1.1.3 version
=> MODDCB-128 Post release 1.1.3

pom.xml, src/main/java/org/folio/dcb/service/impl/UserServiceImpl.java, src/test/resources/mappings/users.json
The purpose of the PR is to implement [MODDCB-130](https://folio-org.atlassian.net/browse/MODDCB-130)
The issue is happening only when we have special characters in the barcode. To make it work, We are using folio util cqlEncode method.
=> MODDCB-130 Fixing issue in patron barcode with special characters

NEWS.md, pom.xml, src/main/java/org/folio/dcb/service/impl/UserServiceImpl.java, src/test/resources/mappings/users.json
The purpose of the PR is to release fixes of MODDCB-114, MODDCB-119 and MODDCB-130 for Q Csp5
=> MODDCB-132 Release fix for Q Csp5 

NEWS.md, pom.xml
The purpose of the PR is to update News md file and change the snapshot version in master after release of 1.1.4 version
=> MODDCB-132 Post release 1.1.4

NEWS.md, pom.xml, src/main/resources/application.yml
The purpose of the PR is to release fixes of MODDCB-114, MODDCB-119, MODDCB-126 and MODDCB-130 for Q Csp5
=> MODDCB-135 Release fix for Q Csp5

NEWS.md, pom.xml
The purpose of the PR is to update News md file and change the snapshot version in master after release of 1.1.5 version
=> MODDCB-135 Post release 1.1.5

pom.xml, src/main/java/org/folio/dcb/service/impl/UserServiceImpl.java, src/test/resources/mappings/users.json
=> MODDCB-130 Backporting fix to Poppy

descriptors/ModuleDescriptor-template.json
inventory from '13.1' to '14.0'
=> MODDCB-133 - inventory API version update

NEWS.md, descriptors/ModuleDescriptor-template.json
[MODDCB-129](https://folio-org.atlassian.net/browse/MODDCB-129) 
Upgrade the API version in the ModuleDescriptor-template.json:
-`holdings-storage 8.0`
=> [MODDCB-129] Upgrade "holdings-storage" API

descriptors/ModuleDescriptor-template.json
=> MODDCB-136 - Increase memory from 350 to 700 mb

.github/workflows/postgres.yml, pom.xml, src/test/java/org/folio/dcb/FolioDcbApplicationIT.java, src/test/java/org/folio/dcb/context/PostgresTestContainersBeanFactoryPostProcessor.java, src/test/java/org/folio/dcb/controller/BaseIT.java, src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java
=> MODDCB-137 - Upgrade folio spring support version

descriptors/ModuleDescriptor-template.json, pom.xml
=> MODDCB-140 Update pom.xml and interface dependencies for Ramsons

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> MODDCB-140 Ramsons release

pom.xml
=> Fix version issue

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> Release 1.2.1

NEWS.md, pom.xml, src/main/java/org/folio/dcb/service/impl/ServicePointServiceImpl.java, src/test/resources/mappings/inventory.json
=> Ramsons release 1.2.2

src/main/java/org/folio/dcb/service/impl/EcsRequestTransactionsServiceImpl.java, src/main/resources/swagger.api/schemas/CirculationRequest.yaml, src/test/java/org/folio/dcb/controller/EcsRequestTransactionsApiControllerTest.java, src/test/java/org/folio/dcb/utils/EntityUtils.java
MODDCB-152
- ECS requests - add PICKUP role support
- Add Intermediate phase to the circulation request schema
=> MODDCB-152 Support for intermediate requests

src/main/java/org/folio/dcb/service/impl/EcsRequestTransactionsServiceImpl.java, src/test/java/org/folio/dcb/controller/EcsRequestTransactionsApiControllerTest.java, src/test/java/org/folio/dcb/utils/EntityUtils.java
MODDCB-152 Add borrowing pickup role
=> MODDCB-152 Add borrowing pickup role

NEWS.md, pom.xml, src/main/java/org/folio/dcb/service/impl/EcsRequestTransactionsServiceImpl.java, src/main/resources/swagger.api/schemas/CirculationRequest.yaml, src/test/java/org/folio/dcb/controller/EcsRequestTransactionsApiControllerTest.java, src/test/java/org/folio/dcb/utils/EntityUtils.java
Resolves: [MODDCB-157](https://folio-org.atlassian.net/browse/MODDCB-157)
=> MODDCB-157 Release 1.2.4

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dcb/repository/TransactionRepository.java, src/main/java/org/folio/dcb/service/RequestService.java, src/main/java/org/folio/dcb/service/impl/LendingLibraryServiceImpl.java, src/main/java/org/folio/dcb/service/impl/RequestServiceImpl.java, src/main/java/org/folio/dcb/utils/DCBConstants.java, src/test/java/org/folio/dcb/service/LendingLibraryServiceTest.java, src/test/java/org/folio/dcb/service/RequestServiceTest.java, src/test/java/org/folio/dcb/utils/EntityUtils.java
=> UXPROD-5054 - Support DCB Requests on Unavailable Items

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> To release 1.2.6

src/main/java/org/folio/dcb/service/impl/ItemServiceImpl.java, src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java, src/test/java/org/folio/dcb/service/InventoryItemServiceTest.java, src/test/resources/mappings/inventory.json
https://folio-org.atlassian.net/browse/MODDCB-159
=> MODDCB-159: url encoding fixed for barcode

NEWS.md, README.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/dcb/client/feign/InventoryServicePointClient.java, src/main/java/org/folio/dcb/domain/converter/IntervalIdEnumConverter.java, src/main/java/org/folio/dcb/domain/entity/ServicePointExpirationPeriodEntity.java, src/main/java/org/folio/dcb/repository/ServicePointExpirationPeriodRepository.java, src/main/java/org/folio/dcb/service/ServicePointExpirationPeriodService.java, src/main/java/org/folio/dcb/service/impl/CustomTenantService.java, src/main/java/org/folio/dcb/service/impl/ServicePointExpirationPeriodServiceImpl.java, src/main/java/org/folio/dcb/service/impl/ServicePointServiceImpl.java, src/main/java/org/folio/dcb/utils/DCBConstants.java, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/create-service-point-expiration-period-table.sql, src/main/resources/db/changelog/changes/create-service-point-expiration-period-table.xml, src/main/resources/swagger.api/schemas/IntervalIdEnum.yaml, src/main/resources/swagger.api/schemas/ServicePointRequest.yaml, src/main/resources/swagger.api/schemas/servicePointExpirationPeriod.yaml, src/test/java/org/folio/dcb/domain/converter/IntervalIdEnumConverterTest.java, src/test/java/org/folio/dcb/service/CustomTenantServiceTest.java, src/test/java/org/folio/dcb/service/ServicePointExpirationPeriodServiceTest.java, src/test/java/org/folio/dcb/service/ServicePointServiceTest.java, src/test/java/org/folio/dcb/utils/EntityUtils.java, src/test/resources/mappings/inventory.json
=> To release 1.1.8

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/dcb/client/feign/CirculationClient.java, src/main/java/org/folio/dcb/client/feign/CirculationLoanPolicyStorageClient.java, src/main/java/org/folio/dcb/service/impl/TransactionsServiceImpl.java, src/main/resources/swagger.api/dcb_transaction.yaml, src/main/resources/swagger.api/schemas/Loan.yaml, src/main/resources/swagger.api/schemas/LoanPolicy.yaml, src/main/resources/swagger.api/schemas/dcbItem.yaml, src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java
https://folio-org.atlassian.net/browse/MODDCB-173
=> MODDCB-173: The GET status API extended with renewal count and renewal maximum number in the borrowing or borrowing-pickup role and ITEM_CHECKED_OUT.

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> Update NEWS.md file and versions

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/dcb/client/feign/CirculationClient.java, src/main/java/org/folio/dcb/client/feign/CirculationLoanPolicyStorageClient.java, src/main/java/org/folio/dcb/controller/TransactionApiController.java, src/main/java/org/folio/dcb/service/TransactionsService.java, src/main/java/org/folio/dcb/service/impl/TransactionsServiceImpl.java, src/main/java/org/folio/dcb/utils/TransactionDetailsUtil.java, src/main/resources/swagger.api/dcb_transaction.yaml, src/main/resources/swagger.api/schemas/Loan.yaml, src/main/resources/swagger.api/schemas/LoanPolicy.yaml, src/main/resources/swagger.api/schemas/RenewByIdRequest.yaml, src/main/resources/swagger.api/schemas/RenewByIdResponse.yaml, src/main/resources/swagger.api/schemas/dcbItem.yaml, src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java, src/test/java/org/folio/dcb/service/TransactionServiceTest.java
=> To release 1.2.8

src/main/resources/db/changelog/changes/create-service-point-expiration-period-table.sql
[MODDCB-194](https://folio-org.atlassian.net/browse/MODDCB-194)
=> MODDCB-194 fixed extension creation

src/main/java/org/folio/dcb/utils/TransactionHelper.java, src/test/java/org/folio/dcb/listener/CirculationRequestEventListenerTest.java, src/test/resources/mockdata/kafka/check_in_awaiting_delivery.json
https://folio-org.atlassian.net/browse/MODDCB-197
Handle `Open - Awaiting delivery` status the same as `Open - Awaiting pickup`
=> MODDCB-197 Support for Open - Awaiting delivery request status

pom.xml
Sets the latest version for mod-dcb as v2.0.0-SNAPSHOT
- Update a module version in pom.xml
=> Update snapshot version to v2.0.0-SNAPSHOT

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/create-pgcrypto-extension.sql, src/main/resources/db/changelog/changes/create-pgcrypto-extension.xml, src/main/resources/db/changelog/changes/create-service-point-expiration-period-table.sql, src/main/resources/db/changelog/changes/create-service-point-expiration-period-table.xml
https://folio-org.atlassian.net/browse/MODDCB-199
=> MODDCB-199: fix liquibase checksum issue for create-service-point-exiration-period-table.xml

NEWS.md, pom.xml, src/main/java/org/folio/dcb/utils/TransactionHelper.java, src/test/java/org/folio/dcb/listener/CirculationRequestEventListenerTest.java, src/test/resources/mockdata/kafka/check_in_awaiting_delivery.json
Resolves: [MODDCB-201](https://folio-org.atlassian.net/browse/MODDCB-201)
=> MODDCB-201 Release 1.2.10

NEWS.md, pom.xml, src/main/java/org/folio/dcb/domain/entity/TransactionEntity.java, src/main/java/org/folio/dcb/domain/mapper/TransactionMapper.java, src/main/java/org/folio/dcb/listener/kafka/CirculationEventListener.java, src/main/java/org/folio/dcb/listener/kafka/EventData.java, src/main/java/org/folio/dcb/repository/TransactionRepository.java, src/main/java/org/folio/dcb/service/impl/BaseLibraryService.java, src/main/java/org/folio/dcb/utils/DCBConstants.java, src/main/java/org/folio/dcb/utils/KafkaEvent.java, src/main/java/org/folio/dcb/utils/TransactionHelper.java, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/add-selfBorrowing-column-into-transaction.xml, src/main/resources/swagger.api/schemas/dcbTransaction.yaml, src/test/java/org/folio/dcb/controller/TransactionApiControllerTest.java, src/test/java/org/folio/dcb/listener/CirculationLoanEventListenerTest.java, src/test/java/org/folio/dcb/service/BaseLibraryServiceTest.java, src/test/java/org/folio/dcb/utils/EntityUtils.java, src/test/resources/mockdata/kafka/loan_check_in_dcb_false.json
Ramsons R2 2024
https://folio-org.atlassian.net/browse/MODDCB-205
=> Ramsons release 1.2.11

NEWS.md, pom.xml
update dependencies versions
bump spring boot to v3.5
=> MODDCB-208: Bump Spring-Boot to 3.5 and update other dependencies

.github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml
- to have in place the process for automation of the updates of dependent modules
- to have standardized approach for all the Pull Requests created for the modules of volaris team
- add dependabot.yml config file
- add PULL_REQUEST_TEMPLATE.md file
[MODDCB-203](https://folio-org.atlassian.net/browse/MODDCB-203)
=> MODDCB-203: Add config file for dependabot and template for pull request

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/resources/swagger.api/schemas/dcbItem.yaml, src/test/java/org/folio/dcb/service/TransactionServiceTest.java
https://folio-org.atlassian.net/browse/MODDCB-206
[MODDCB-XXX](https://folio-org.atlassian.net/browse/MODDCB-XXX)
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._
=> MODDCB-206: Populate locationCode for DCB Transaction API

NEWS.md, descriptors/ModuleDescriptor-template.json
item-storage api was updated with a breaking change and thus bump the version of `item-storage` to 11.0 version.
- update the version of `item-storage` dependency in module descriptor.
[MODDCB-216](https://folio-org.atlassian.net/browse/MODDCB-216)
=> MODDCB-216: item storage api version update

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
https://folio-org.atlassian.net/browse/MODDCB-220
[MODDCB-220](https://folio-org.atlassian.net/browse/MODDCB-220)
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._
=> Ramsons release 1.2.12

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
https://folio-org.atlassian.net/browse/MODDCB-221
[MODDCB-221](https://folio-org.atlassian.net/browse/MODDCB-221)
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._
=> Sunflower release 1.3.4

NEWS.md, descriptors/ModuleDescriptor-template.json
To add missing permission in DCB transaction status API
1. Added `circulation-storage.loan-policies.collection.get` modulePermissions for GET transaction status API. 
[MODDCB-223](https://folio-org.atlassian.net/browse/MODDCB-223)
_If this pull request involves any visual changes or new features, consider including screenshots …
=> MODDCB-223: Added missing permission for transactions status API

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
https://folio-org.atlassian.net/browse/MODDCB-224
https://folio-org.atlassian.net/browse/MODDCB-224
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._
=> Ramsons release 1.2.13
